# Generated by Django 5.0.4 on 2024-06-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticPoint',
            fields=[
                ('logistic_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('input', models.BooleanField(default=False)),
                ('output', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(default='')),
                ('mass', models.DecimalField(decimal_places=2, default='0', max_digits=100)),
                ('width', models.DecimalField(decimal_places=2, default='0', max_digits=100)),
                ('length', models.DecimalField(decimal_places=2, default='0', max_digits=100)),
                ('height', models.DecimalField(decimal_places=2, default='0', max_digits=100)),
                ('cost', models.DecimalField(decimal_places=2, default='0', max_digits=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(default='-', max_length=50)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('passport', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('warehouse_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_list_num', models.TextField()),
                ('description', models.TextField()),
                ('num_steps', models.IntegerField()),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='bankatest.logisticpoint')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='bankatest.logisticpoint')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('order_step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField(default='0.0')),
                ('location_type', models.TextField(default='0.0')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('product_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_list_num', models.TextField(default='')),
                ('count', models.DecimalField(decimal_places=2, default='1', max_digits=155)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_card', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.userinfo'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_num', models.TextField(default='0')),
                ('vehicle_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_num', models.TextField(default='NULL')),
                ('warehouse_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.warehousetype')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.user')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_num', models.TextField(default='NULL')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankatest.worker')),
            ],
        ),
    ]
