# Generated by Django 5.0.4 on 2024-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankatest', '0003_worker_garage_worker_work_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstep',
            name='distanse',
            field=models.IntegerField(default=0),
        ),
    ]
